# Generated by Django 2.0.3 on 2018-07-09 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainTsint', '0029_censysanddomaindb_score'),
        ('myIt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingNormDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactEmail', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('expiresDate', models.CharField(blank=True, max_length=100, null=True)),
                ('fraudDomain', models.CharField(blank=True, max_length=100, null=True)),
                ('fraudScore', models.IntegerField()),
                ('nameServers', models.CharField(blank=True, max_length=100, null=True)),
                ('registrantName', models.CharField(blank=True, max_length=100, null=True)),
                ('registrantOrg', models.CharField(blank=True, max_length=100, null=True)),
                ('registrarName', models.CharField(blank=True, max_length=100, null=True)),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='domainTsint.Domain')),
            ],
        ),
    ]

